version: '3.11'
services:
  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - mydata:/app/data 

  # myApp
  cron-z2y-django:
    image: $Z2Y_IMAGE
    container_name: cron-z2y-django
    volumes:
      - mydata:/app/data
      - static:/app/staticfiles
      - media:/app/media
    ports:
      - "5000:5000"

  # Celery
  celery:
    restart: always
    image: z2y_celery_django
    container_name: celery
    command: celery -A backend worker -l INFO
    depends_on:
      - redis
      - cron-z2y-django
    volumes:
      - mydata:/app/data
volumes:
  mydata:
  static:
  media:
