version: '3.11'
services:
  # database
  #db:
    #image: postgres:alpine
    #container_name: db
    #ports:
     # - "5433:5432"
    #env_file:
     # - .env
    #volumes:
    #  - mydata:/var/lib/postgresql/data
    #environment:
     # - POSTGRES_USER=postgres
    #  - POSTGRES_PASSWORD=postgres
   #   - POSTGRES_DB=postgres

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - mydata:/app/data

  # myApp
  cron-zoom-youtube-django:
    #build: ./
    image: $ZOOM_YOUTUBE_INTEGRATION_IMAGE
    container_name: cron-z2y-django
    volumes:
      - mydata:/app/data
      - static:/app/staticfiles
      - media:/app/media
    #env_file:
      #- .env
    ports:
      - "5000:5000"
    #environment:
     # - DB_HOST=db
      #- DB_NAME=postgres
      #- DB_USER=postgres
     # - DB_PASSWORD=postgres
    #depends_on:
     # - db

  # Celery
  celery:
    restart: always
    build: ./
    container_name: celery
    command: celery -A backend worker -l INFO
    depends_on:
     # - db
      - redis
      - cron-zoom-youtube-django
    volumes:
      - mydata:/app/data
volumes:
  mydata:
  static:
  media:
