version: "3.11"
services:
  mysqldb-docker:
    image: mysql:latest
    container_name: my_mysql
    restart: 'unless-stopped'
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - "3333:3306"    
  
    environment: 
      MYSQL_ROOT_PASSWORD: root_password@mysql
      MYSQL_DATABASE: mydjango-database
      MYSQL_USER: root
      MYSQL_HOST: localhost
          

  # Redis
  redis-james-django-chukwu:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - mydata:/app/data

  # myApp
  cron-z2y-django:
    build: ./
    image: $Z2Y_IMAGE
    container_name: cron-z2y-django
    volumes:
      - mydata:/app/data
      - static:/app/staticfiles
      - media:/app/media
    ports:
      - "5000:80"
    #env_file:
     # - .env
    #environment:
     # - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      #- DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      #- DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}

  # Celery
  celery:
    restart: always
    build: ./
    container_name: celery
    command: celery -A backend worker -l INFO
    depends_on:
      - redis-james-django-chukwu
      - cron-z2y-django
    volumes:
      - mydata:/app/data

volumes:
  mysqldb:
  mydata:
  static:
  media:
