WSGIPythonPath /django_app
WSGIPassAuthorization On
Listen 8081

<VirtualHost *:80>
        ServerAdmin admin@gmail.com
        ServerName localhost
        DocumentRoot /django_app
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        
        Alias /static /django_app/static
        <Directory /django_app/static>
                Require all granted
        </Directory>
    
	<Directory /django_app/backend/>
		<Files wsgi.py>
			Require all granted
		</Files>
	</Directory>   
	WSGIApplicationGroup %{GLOBAL}     
        WSGIScriptAlias / /django_app/backend/wsgi.py
</VirtualHost>
