"""
Django's settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', cast=str)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['zoomvideoautomation.bincom.net', '40.117.178.47','localhost',]  # added domain name and ip adress


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MY_APPS = [
    'core.apps.CoreConfig',
]

THIRD_PARTY = [
    'jazzmin',
    'widget_tweaks',
]

INSTALLED_APPS = THIRD_PARTY + DJANGO_APPS + MY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# logging
"""
Version is the number log 
Django uses some of its own loggers for internal operations. 
In case you want to disable them just replace the False above with True.
A handler for WARNING. It is basically writing the WARNING messages into a file called WARNING.log

"""

# Logging settings
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'cron_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': '/cron/cron.log',  # Replace with the desired path to your log file
        },
    },
    'loggers': {
        'django': {
            'handlers': ['cron_file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'new-mysql',
        'USER': 'root',
        'PASSWORD': 'root_password@mysql',
        'HOST': 'db',
        'PORT': 3306,
    }
}

#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.postgresql',
   #     'NAME': config('DB_NAME'),
    #    'USER': config('DB_USER'),
     #   'PASSWORD': config('DB_PASSWORD'),
      #  'HOST': config('DB_HOST'),
       # 'PORT': 5432,
   # }
#}


# Passwords validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
#STATICFILES_DIRS = [BASE_DIR/'static']
#STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_ROOT = os.path.join(BASE_DIR, "static")  # added this

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR/"media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'main:admin_login'
LOGIN_REDIRECT_URL = 'main:home'
LOGOUT_REDIRECT_URL = 'main:admin_login'

"""
On production, For the email settings, ensure you set accordingly to django protocol: Gmail, Yahoo or Onedrive.
For now it is using the console command
"""
# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = ''
EMAIL_PORT = 465  # 587 is for TLS
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'localhost'
EMAIL_HOST_PASSWORD = ''


CORS_ALLOWED_ORIGINS = ['https://zoomvideoautomation.bincom.net',"http://localhost"]  # added this

CSRF_TRUSTED_ORIGINS = ['https://zoomvideoautomation.bincom.net',"http://localhost"]  # added this

# Celery settings
CELERY_BROKER_URL = "redis://redis-james-django-chukwu:6379"
CELERY_RESULT_BACKEND = "redis://redis-james-django-chukwu:6379"

# google credentials
ENABLE_VIDEO_CONVERTING = os.environ.get("ENABLE_VIDEO_CONVERTING", "off") == "on"  # converts the zoom recorded videos to YouTube video format

# zoom credentials
FILTER_MEETING_BY_NAME = os.environ.get("FILTER_MEETING_BY_NAME", "false").lower() in ["true", "on", "1"]
ONLY_MEETING_NAMES = [n.strip() for n in os.environ.get("ONLY_MEETING_NAMES", "").split(",")]

# video directory to save the zoom recorded videos
VIDEO_DIR = os.path.join(BASE_DIR, "video")

# download folder for zoom cloud recordings to database
DOWNLOADED_FILES = os.path.join(BASE_DIR, 'downloaded')

# Jazzmin settings
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "ZoomVideoYouTubeAutomation Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Developer Base",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Bincom",

    # Welcome text on the login screen
    "welcome_sign": "I am a Developer",

    # Copyright on the footer
    "copyright": "Bincom Dev Center",
}
